/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  CurrencyAmount,
} from './models/currency-amount';

export namespace Components {
  interface CurrencyFormatter {
    /**
    * The CurrencyAmount object that is intended to be formatted.
    */
    'currencyAmount': CurrencyAmount;
    /**
    * Parameter that defines user language.
    */
    'locale': string;
  }
  interface TrainingApp {}
}

declare global {


  interface HTMLCurrencyFormatterElement extends Components.CurrencyFormatter, HTMLStencilElement {}
  var HTMLCurrencyFormatterElement: {
    prototype: HTMLCurrencyFormatterElement;
    new (): HTMLCurrencyFormatterElement;
  };

  interface HTMLTrainingAppElement extends Components.TrainingApp, HTMLStencilElement {}
  var HTMLTrainingAppElement: {
    prototype: HTMLTrainingAppElement;
    new (): HTMLTrainingAppElement;
  };
  interface HTMLElementTagNameMap {
    'currency-formatter': HTMLCurrencyFormatterElement;
    'training-app': HTMLTrainingAppElement;
  }
}

declare namespace LocalJSX {
  interface CurrencyFormatter extends JSXBase.HTMLAttributes<HTMLCurrencyFormatterElement> {
    /**
    * The CurrencyAmount object that is intended to be formatted.
    */
    'currencyAmount'?: CurrencyAmount;
    /**
    * Parameter that defines user language.
    */
    'locale'?: string;
  }
  interface TrainingApp extends JSXBase.HTMLAttributes<HTMLTrainingAppElement> {}

  interface IntrinsicElements {
    'currency-formatter': CurrencyFormatter;
    'training-app': TrainingApp;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


