/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface TrainingApp {}
}

declare global {


  interface HTMLTrainingAppElement extends Components.TrainingApp, HTMLStencilElement {}
  var HTMLTrainingAppElement: {
    prototype: HTMLTrainingAppElement;
    new (): HTMLTrainingAppElement;
  };
  interface HTMLElementTagNameMap {
    'training-app': HTMLTrainingAppElement;
  }
}

declare namespace LocalJSX {
  interface TrainingApp extends JSXBase.HTMLAttributes<HTMLTrainingAppElement> {}

  interface IntrinsicElements {
    'training-app': TrainingApp;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


